#!/usr/bin/env python3
#
# kcri.bap.shims.versions - generated by update-backends.sh.
# Used by the shims to report their backend service version.
#
BACKEND_VERSIONS = dict()
BACKEND_VERSIONS["cge_core_module"] = "cleanup-tmpdirs"
BACKEND_VERSIONS["cgmlstfinder"] = "1.1.0.11"
BACKEND_VERSIONS["choleraefinder"] = "1.0.0.1"
BACKEND_VERSIONS["kmerfinder"] = "3.0.2.3"
BACKEND_VERSIONS["mlst"] = "2.0.4.4"
BACKEND_VERSIONS["plasmidfinder"] = "2.0.1.18"
BACKEND_VERSIONS["pmlst"] = "2.0.1.5"
BACKEND_VERSIONS["resfinder"] = "4.1.0.10"
BACKEND_VERSIONS["virulencefinder"] = "2.0.3.11"
BACKEND_VERSIONS["kma"] = "1.3.9"
BACKEND_VERSIONS["kcst"] = "1.2.5"
BACKEND_VERSIONS["skesa"] = "2.4.0-8-g9a75"
BACKEND_VERSIONS["picoline"] = "1.0.0"
BACKEND_VERSIONS["fastq-utils"] = "1.1.0"
BACKEND_VERSIONS["unfasta"] = "1.1.1"
BACKEND_VERSIONS["odds-and-ends"] = "1.0.0"
BACKEND_VERSIONS["ncbi-blast"] = "2.11.0"
