#!/usr/bin/env python3
#
# kcri.bap.shims.versions - generated by update-backends.sh.
# Used by the shims to report their backend service version.
#
BACKEND_VERSIONS = dict()
BACKEND_VERSIONS["cgecore"] = "cleanup-tmpdirs"
BACKEND_VERSIONS["cgelib"] = "0.7.3-3-ged9a"
BACKEND_VERSIONS["cgmlstfinder"] = "1.1.5.11"
BACKEND_VERSIONS["choleraefinder"] = "1.0.0.2"
BACKEND_VERSIONS["kmerfinder"] = "3.0.2.4"
BACKEND_VERSIONS["mlst"] = "2.0.9.0"
BACKEND_VERSIONS["plasmidfinder"] = "2.1.6.1"
BACKEND_VERSIONS["pmlst"] = "2.0.3.1"
BACKEND_VERSIONS["resfinder"] = "4.2.3.12"
BACKEND_VERSIONS["virulencefinder"] = "2.0.4.4"
BACKEND_VERSIONS["flye"] = "2.9.1-1-g4bb3"
BACKEND_VERSIONS["kma"] = "1.4.9"
BACKEND_VERSIONS["kcst"] = "1.2.6-1-g24db"
BACKEND_VERSIONS["skesa"] = "skesa.2.4.0_saute.1.3.0_2"
BACKEND_VERSIONS["picoline"] = "1.4.2"
BACKEND_VERSIONS["fastq-utils"] = "1.3.0"
BACKEND_VERSIONS["unfasta"] = "1.3.1"
BACKEND_VERSIONS["odds-and-ends"] = "1.0.1-1-g5da2"
BACKEND_VERSIONS["ncbi-blast"] = "2.13.0"
